# Generated by Django 5.2 on 2025-05-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad_actual', models.PositiveIntegerField()),
                ('edad_retiro', models.PositiveIntegerField()),
                ('saldo_acumulado', models.FloatField()),
                ('ahorro_mensual', models.FloatField()),
            ],
        ),
    ]
