# Generated by Django 5.2 on 2025-05-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
